const tableData = [
    {
        pid: '0',
        vegetationName: '动物园园区内',
        vegetationLevel: '一级',
        totalArea: '542',
        conservationArea: '4623626.64',
        normalBuildingArea: '41064.26',
        classicalBuildingArea: '0',
        gardenRoadArea: '51154.1',
        squareArea: '579046',
        waterArea: '26758',
        otherArea: '97490.96',
        toiletDistribution: '8/860',
        remark: ''
    },
    {
        pid: '1',
        vegetationName: '锡林公园',
        vegetationLevel: '一级',
        totalArea: '29.06',
        conservationArea: '193806',
        normalBuildingArea: '3971',
        classicalBuildingArea: '0',
        gardenRoadArea: '42429',
        squareArea: '19322',
        waterArea: '31100',
        otherArea: '0',
        toiletDistribution: '2/300',
        remark: '其中1处厕所权属归玉泉区'
    },
    {
        pid: '2',
        vegetationName: '公主府公园滨河绿地',
        vegetationLevel: '一级',
        totalArea: '3.79',
        conservationArea: '27005',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '10895',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '3',
        remark: '厕所为城市综合体'
    },
    {
        pid: '2',
        vegetationName: '公主府公园小府绿地',
        vegetationLevel: '一级',
        totalArea: '3.66',
        conservationArea: '28400',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '6562',
        waterArea: '1638',
        otherArea: '',
        toiletDistribution: '',
        remark: ''
    },
    {
        pid: '2',
        vegetationName: '公主府公园和硕绿地',
        vegetationLevel: '一级',
        totalArea: '0.72',
        conservationArea: '6000',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '1200',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '1',
        remark: '厕所为临建公厕'
    },
    {
        pid: '2',
        vegetationName: '滨河绿地-通道街游园',
        vegetationLevel: '一级',
        totalArea: '1.5309',
        conservationArea: '13051.22',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '2257.78',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '',
        remark: ''
    },
    {
        pid: '2',
        vegetationName: '公主府公园河东绿地',
        vegetationLevel: '一级',
        totalArea: '1.7926',
        conservationArea: '11192',
        normalBuildingArea: '100',
        classicalBuildingArea: '0',
        gardenRoadArea: '793',
        squareArea: '4872',
        waterArea: '969',
        otherArea: '0',
        toiletDistribution: '1/100',
        remark: '厕所归属为城环公司'
    },
    {
        pid: '3',
        vegetationName: '河道两侧绿地(G6以南）及河道',
        vegetationLevel: '一级',
        totalArea: '825',
        conservationArea: '4170532',
        normalBuildingArea: '300556',
        classicalBuildingArea: '2205',
        gardenRoadArea: '321294',
        squareArea: '251358',
        waterArea: '3204995',
        otherArea: '0',
        toiletDistribution: '60/4193',
        remark: '其中本单位管理的公厕有13个，其余47个为在环城水系管辖绿地范围内，但不属于本单位管理'
    },
    {
        pid: '3',
        vegetationName: '敕勒川公园',
        vegetationLevel: '一级',
        totalArea: '36.3',
        conservationArea: '250798',
        normalBuildingArea: '2429',
        classicalBuildingArea: '0',
        gardenRoadArea: '46869',
        squareArea: '34417',
        waterArea: '27249',
        otherArea: '1736',
        toiletDistribution: '6/517',
        remark: '其中本单位管理的公厕有4个，其余2个为在环城水系管辖绿地范围内，但不属于本单位管理'
    },
    {
        pid: '3',
        vegetationName: '党校绿地',
        vegetationLevel: '一级',
        totalArea: '13.4836',
        conservationArea: '124336',
        normalBuildingArea: '100',
        classicalBuildingArea: '0',
        gardenRoadArea: '8000',
        squareArea: '2400',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '1/60',
        remark: '该公厕为在环城水系管辖绿地范围内，但不属于本单位管理'
    },
    {
        pid: '3',
        vegetationName: '保全庄桥头',
        vegetationLevel: '一级',
        totalArea: '3.673',
        conservationArea: '35530',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '1200',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '3',
        vegetationName: '广电广场绿化及水域',
        vegetationLevel: '一级',
        totalArea: '4.4863',
        conservationArea: '19712',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '970',
        squareArea: '306',
        waterArea: '23875',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '3',
        vegetationName: '大学东街',
        vegetationLevel: '一级',
        totalArea: '0.41',
        conservationArea: '4100',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '3',
        vegetationName: '滨河公园',
        vegetationLevel: '一级',
        totalArea: '1.3977',
        conservationArea: '11514',
        normalBuildingArea: '27',
        classicalBuildingArea: '0',
        gardenRoadArea: '720',
        squareArea: '1716',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '2/80',
        remark: ''
    },
    {
        pid: '4',
        vegetationName: '满都海公园',
        vegetationLevel: '一级',
        totalArea: '18',
        conservationArea: '101000',
        normalBuildingArea: '2200',
        classicalBuildingArea: '500',
        gardenRoadArea: '13000',
        squareArea: '20000',
        waterArea: '46000',
        otherArea: '0',
        toiletDistribution: '4/255',
        remark: ''
    },
    {
        pid: '5',
        vegetationName: '青城公园',
        vegetationLevel: '一级',
        totalArea: '44.82',
        conservationArea: '248200',
        normalBuildingArea: '31973',
        classicalBuildingArea: '1302',
        gardenRoadArea: '37523',
        squareArea: '36700',
        waterArea: '92500',
        otherArea: '0',
        toiletDistribution: '9/668.5',
        remark: ''
    },
    {
        pid: '5',
        vegetationName: '大召广场',
        vegetationLevel: '一级',
        totalArea: '1.93',
        conservationArea: '19300',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '5',
        vegetationName: '玉泉公园',
        vegetationLevel: '一级',
        totalArea: '3.1962',
        conservationArea: '31962',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '5',
        vegetationName: '交校游园',
        vegetationLevel: '一级',
        totalArea: '0.6925',
        conservationArea: '6925',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '5',
        vegetationName: '五塔寺广场',
        vegetationLevel: '一级',
        totalArea: '0.5931',
        conservationArea: '5931',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '4423',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '5',
        vegetationName: '观音庙广场',
        vegetationLevel: '一级',
        totalArea: '0.3302',
        conservationArea: '3302',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '5',
        vegetationName: '席力图召广场',
        vegetationLevel: '一级',
        totalArea: '0.15',
        conservationArea: '1500',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '5',
        vegetationName: '佳和游园',
        vegetationLevel: '一级',
        totalArea: '2.2229',
        conservationArea: '22229',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '锡林路游园',
        vegetationLevel: '一级',
        totalArea: '2.61',
        conservationArea: '16412',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '5165',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '新华大街与西二环交叉路口绿地',
        vegetationLevel: '一级',
        totalArea: '4.65',
        conservationArea: '16600',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '16600',
        waterArea: '13900',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '鄂尔多斯大街与西二环交叉口绿地',
        vegetationLevel: '一级',
        totalArea: '2.0005',
        conservationArea: '11205',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '5000',
        waterArea: '3800',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '正泰小区游园(东二环)',
        vegetationLevel: '一级',
        totalArea: '4.1',
        conservationArea: '33320',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '7680',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '东二环与敕勒川大街交叉口节点绿地(东二环)',
        vegetationLevel: '一级',
        totalArea: '1.4',
        conservationArea: '8000',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '6000',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '会展广场游园',
        vegetationLevel: '一级',
        totalArea: '2.74',
        conservationArea: '24975',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '2426',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '芥子园',
        vegetationLevel: '一级',
        totalArea: '1.9',
        conservationArea: '16948',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '2052',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '永恒之门广场及周边绿化',
        vegetationLevel: '一级',
        totalArea: '3.4012',
        conservationArea: '14012',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '20000',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '呼伦南路公园',
        vegetationLevel: '一级',
        totalArea: '1.22',
        conservationArea: '9500',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '1400',
        squareArea: '1300',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '富泰加压站绿地(东二环)',
        vegetationLevel: '一级',
        totalArea: '0.27',
        conservationArea: '1956',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '750',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '北二环成吉思汗公园东南角绿地',
        vegetationLevel: '一级',
        totalArea: '3.35',
        conservationArea: '33500',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '东二环科技馆绿地',
        vegetationLevel: '一级',
        totalArea: '0.32',
        conservationArea: '3200',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '南二环与锡林路交叉口北侧绿地',
        vegetationLevel: '一级',
        totalArea: '0.8908',
        conservationArea: '5975.4',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '2932.6',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '三毛游园',
        vegetationLevel: '一级',
        totalArea: '0.5099',
        conservationArea: '4201',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '898',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '丰瑞1号游园',
        vegetationLevel: '一级',
        totalArea: '0.9886',
        conservationArea: '5186',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '4700',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '阿吉纳游园',
        vegetationLevel: '一级',
        totalArea: '2.89',
        conservationArea: '28900',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '广电大厦前绿地',
        vegetationLevel: '一级',
        totalArea: '4.6326',
        conservationArea: '46326',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '财院东墙绿地',
        vegetationLevel: '一级',
        totalArea: '0.6496',
        conservationArea: '6496',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '铁木真游园',
        vegetationLevel: '一级',
        totalArea: '2.6021',
        conservationArea: '26021',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '哲里木路游园',
        vegetationLevel: '一级',
        totalArea: '1.4313',
        conservationArea: '14313',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '美术馆游园',
        vegetationLevel: '一级',
        totalArea: '2.80169',
        conservationArea: '28016',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '隆庆钢材市场',
        vegetationLevel: '一级',
        totalArea: '2.8957',
        conservationArea: '28957',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '东河上的院子',
        vegetationLevel: '一级',
        totalArea: '4.0815',
        conservationArea: '408153',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '中海地产',
        vegetationLevel: '一级',
        totalArea: '0.79',
        conservationArea: '7900',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '八里庄游园',
        vegetationLevel: '一级',
        totalArea: '1.7708',
        conservationArea: '17708',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '八彦路',
        vegetationLevel: '一级',
        totalArea: '0.6017',
        conservationArea: '6017',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '乌素图游园',
        vegetationLevel: '一级',
        totalArea: '5.7918',
        conservationArea: '57918',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '6',
        vegetationName: '岱洲营游园',
        vegetationLevel: '一级',
        totalArea: '4.7128',
        conservationArea: '47128',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '0',
        squareArea: '0',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '0',
        remark: ''
    },
    {
        pid: '7',
        vegetationName: '呼和浩特市湿地公园',
        vegetationLevel: '一级',
        totalArea: '411.86',
        conservationArea: '3014507',
        normalBuildingArea: '8193',
        classicalBuildingArea: '0',
        gardenRoadArea: '89120',
        squareArea: '141681',
        waterArea: '865099',
        otherArea: '0',
        toiletDistribution: '10/983.98',
        remark: ''
    },
    {
        pid: '8',
        vegetationName: '新华公园',
        vegetationLevel: '一级',
        totalArea: '13.53',
        conservationArea: '93699',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '12472',
        squareArea: '19356',
        waterArea: '9772',
        otherArea: '0',
        toiletDistribution: '2/195',
        remark: ''
    },
    {
        pid: '9',
        vegetationName: '草原丝绸之路文化公园',
        vegetationLevel: '一级',
        totalArea: '80',
        conservationArea: '567000',
        normalBuildingArea: '2000',
        classicalBuildingArea: '500',
        gardenRoadArea: '160000',
        squareArea: '53000',
        waterArea: '20000',
        otherArea: '0',
        toiletDistribution: '4/1000',
        remark: ''
    },
    {
        pid: '10',
        vegetationName: '阿尔泰游乐园',
        vegetationLevel: '一级',
        totalArea: '55.34',
        conservationArea: '427200',
        normalBuildingArea: '2500',
        classicalBuildingArea: '0',
        gardenRoadArea: '20000',
        squareArea: '89000',
        waterArea: '14700',
        otherArea: '0',
        toiletDistribution: '5/765.5',
        remark: '3新2旧'
    },
    {
        pid: '11',
        vegetationName: '新钢公园',
        vegetationLevel: '一级',
        totalArea: '30.3',
        conservationArea: '225800',
        normalBuildingArea: '607.5',
        classicalBuildingArea: '0',
        gardenRoadArea: '16176',
        squareArea: '53824',
        waterArea: '7200',
        otherArea: '0',
        toiletDistribution: '4/428',
        remark: ''
    },
    {
        pid: '11',
        vegetationName: '府兴游园',
        vegetationLevel: '一级',
        totalArea: '6.843',
        conservationArea: '46630',
        normalBuildingArea: '0',
        classicalBuildingArea: '0',
        gardenRoadArea: '1913',
        squareArea: '19887',
        waterArea: '0',
        otherArea: '0',
        toiletDistribution: '1/150',
        remark: ''
    },
    {
        pid: '11',
        vegetationName: '北郊、希贵图公园',
        vegetationLevel: '一级',
        totalArea: '36.16',
        conservationArea: '326000',
        normalBuildingArea: '210',
        classicalBuildingArea: '0',
        gardenRoadArea: '19034',
        squareArea: '10966',
        waterArea: '5600',
        otherArea: '0',
        toiletDistribution: '6/1095',
        remark: ''
    },
    {
        pid: '12',
        vegetationName: '成吉思汗公园',
        vegetationLevel: '一级',
        totalArea: '59.04',
        conservationArea: '475100',
        normalBuildingArea: '4151',
        classicalBuildingArea: '0',
        gardenRoadArea: '13627',
        squareArea: '63062',
        waterArea: '22800',
        otherArea: '11400',
        toiletDistribution: '3/260',
        remark: ''
    }
]

export default tableData;